{% set name = "r-partitions" %}
{% set version = "1.9-22" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}
{% set sha256 = "da020f447e669f273207fdc0f56dde90ca7082cc5f89531ec0c473245c231ee3" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/partitions_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/partitions/partitions_{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base >=3.6.0
    - r-sets
    - r-gmp
    - r-polynom
  run:
    - r-base >=3.6.0
    - r-sets
    - {{native}}gcc-libs         # [win]
    - r-gmp
    - r-polynom

test:
  commands:
    - $R -e "library('partitions')"           # [not win]
    - "\"%R%\" -e \"library('partitions')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=partitions
  license: GPL
  summary: Additive partitions of integers.
  license_family: GPL
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - npavlovikj
