{% set version = "1.10-4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-partitions
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/partitions_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/partitions/partitions_{{ version }}.tar.gz
  sha256: b10091416c3453eb9e9fd46c8cdd35668236579676db43d0267d79e7856467c6

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-eddington
    - r-gmp
    - r-mathjaxr
    - r-polynom
    - r-sets
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-eddington
    - r-gmp
    - r-mathjaxr
    - r-polynom
    - r-sets

test:
  commands:
    - $R -e "library('partitions')"           # [not win]
    - "\"%R%\" -e \"library('partitions')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=partitions
  license: GPL-2.0-or-later
  summary: Additive partitions of integers.
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - npavlovikj
