{% set name = "r-partitions" %}
{% set version = "1.10-1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}
{% set sha256 = "7f81ebc99418c4f158b01e66b5f9f16be8cace635952be309d092664700d8c2d" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/partitions_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/partitions/partitions_{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-gmp
    - r-polynom
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-gmp
    - r-polynom

test:
  commands:
    - $R -e "library('partitions')"           # [not win]
    - "\"%R%\" -e \"library('partitions')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=partitions
  license: GPL-3.0
  summary: Additive partitions of integers.
  license_family: GPL
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - npavlovikj
