{% set version = "1.10-9" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-partitions
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/partitions_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/partitions/partitions_{{ version }}.tar.gz
  sha256: 1a2dcded62592508932138d5233b6acd21fdde128dd55c907e07464a42ad1c21

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rdpack
    - r-gmp
    - r-mathjaxr
    - r-polynom
    - r-sets
  run:
    - r-base
    - r-rdpack
    - r-gmp
    - r-mathjaxr
    - r-polynom
    - r-sets

test:
  commands:
    - $R -e "library('partitions')"           # [not win]
    - "\"%R%\" -e \"library('partitions')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=partitions
  license: GPL-2.0-or-later
  summary: Additive partitions of integers.
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - npavlovikj
