travis:
  secure:
    BINSTAR_TOKEN: e2BiHkSimik3k/VuYaPAGxrIQlBU5hWphd8qTEsu1yI8j+RIzLcAglcdF26UK2yAOsknJnz5KtAw+hjeWk94+teyZOe7btMbv9sNZYw6UIg2iWoP9nan3I0gurNGF+EaLaQPFoNZDe4FtdCNCxRrUpV6W6sulXmwZSkuSTJdX1PHdGTAm9iTO6N31acupv0JGue/OpjMKqERyvykQYOo/Zw21OVWrZ0INFj6IXyQqByXwS3O8CTFT1RotSPsYC5j60GX7YWtalXaS4rwQ8ufiO704SvG58fhQrIBsw/NrJhXMLGED77d+NAfT9HCPgqT/0z7TCSNyQcruOrLVdG88R+NQEUNgV3mLtJAe7lmI2LINis5qUs1t+AUJbCVd/ntaOsu5r/DnhkmBNNqUByQUVdgrx9kdeqsWrYAhPtRKdnt1mickcJ2bGKBK93YrmYsAkB3SEJlwg3L6Qg1fNr2L0Ok0JSgfRcYr6SaQUrpf9G7ppcbtgm7dDjUMZgMMQ91DPjnrleC+zYfmj5U6Bxf21GyXzbYjikB4ra0xnWWYD94rYP3BtIG+F7o6l+bPSvqWGd+RphfmA1GXCkp/HXO7FGWLFneLwxlHNQnNOzdvI5kxVlE33cKMCeaLwpTLaPsu90svxOxKgR4uzYMqUuz9ucOK5mesb9jnsbekwfunTk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
bot:
  automerge: true
